window.MASTERY_DATA = {
  fundamentals: [
    { name: "JavaScript", detail: "objects, arrays, functions, scope, errors, async/Promises, modules, Maps/Sets", first: "P01", anchor: "p01" },
    { name: "APIs & web", detail: "HTTP, REST, OAuth, webhooks, signatures, pagination, rate limits", first: "P01", anchor: "p01" },
    { name: "SQL & state", detail: "joins, indexes, constraints, transactions, migrations, audit logs", first: "P03", anchor: "p03" },
    { name: "Reliability", detail: "idempotency, queues, dead letters, replay, state machines, observability", first: "P02", anchor: "p02" },
    { name: "Security", detail: "secrets, least privilege, AuthN/AuthZ, RBAC, RLS, PII, prompt injection", first: "P01", anchor: "p01" },
    { name: "Operations", detail: "Git, environments, Docker, backups, monitoring, deployment", first: "P07", anchor: "p07" }
  ],
  valueAreas: [
    { label: "Lead-to-cash", note: "Routing, enrichment, CRM hygiene, quote approval, billing handoff.", project: "P02", signal: "Revenue speed" },
    { label: "Finance operations", note: "Invoice/AP/AR matching, exception handling, and audit trails.", project: "P04", signal: "Cash & error risk" },
    { label: "Customer onboarding", note: "Contract or payment to access, tasks, welcome steps, and handoff.", project: "P05", signal: "Time-to-value" },
    { label: "Support & SLA", note: "Classification, escalation, drafting, QA, and human approval.", project: "P06", signal: "Service cost" },
    { label: "Inventory & orders", note: "Multi-system stock/order changes and fulfillment exceptions.", project: "P03", signal: "Operational accuracy" },
    { label: "Control layer", note: "Exception review, approvals, execution history, and tenant-safe visibility.", project: "P08", signal: "Operational scale" }
  ],
  projects: [
    {
      id: "P01", slug: "p01", title: "Webhook Command Center", value: "Reliable intake is the foundation of every serious automation.", build: "Build a signed webhook receiver that validates a lead payload, normalizes it, returns a clear response, and routes bad data to an exception queue.", patterns: ["Webhook", "Set/Edit Fields", "If", "Switch", "Code", "Error Trigger"], fundamentals: ["JSON", "HTTP headers", "status codes", "objects", "functions", "schema validation"], drills: ["Receive a form payload and return a 200 response", "Normalize a nested lead payload in a Code node", "Reject a missing or malformed email with a 400", "Record raw input and normalized output separately"], tests: ["Happy path payload reaches the normalized output", "Malformed JSON produces a visible exception", "Missing email is rejected before any downstream write", "Bad authentication produces a clear 401/403 response", "A timeout or 500 triggers the error workflow"], gate: "You can diagnose a malformed payload, auth error, rate-limit response, and server failure without help.", content: "First working webhook demo: publish what the payload looks like, how it breaks, and how you caught it." },
    {
      id: "P02", slug: "p02", title: "Lead-to-CRM Routing Engine", value: "This is a direct lead-to-cash system: fast response, clean CRM data, and visible ownership.", build: "Build form/webhook → enrichment → lead scoring → CRM upsert → owner routing → Slack notification, with an approval queue for uncertain or high-value leads.", patterns: ["HTTP Request", "Merge", "Loop Over Items", "Switch", "Code", "Wait", "Error Trigger"], fundamentals: ["REST APIs", "API keys vs OAuth", "arrays", "idempotency", "retries", "business rules"], drills: ["Call an enrichment API and map its response", "Upsert a CRM contact by email/domain", "Score a lead with transparent rules", "Route high-value leads to a human approval queue"], tests: ["Duplicate event ID produces no second CRM record", "Same lead on a new event updates rather than duplicates", "Expired credential alerts without losing the event", "429 response backs off and retries within a limit", "A failed CRM write can be replayed safely"], gate: "Duplicate delivery produces exactly one CRM record and every routing decision is auditable.", content: "Portfolio demo: show the duplicate event, the idempotency record, and the single correct CRM outcome." },
    {
      id: "P03", slug: "p03", title: "CRM Data Quality + SLA Engine", value: "Dirty CRM data destroys routing, forecasting, and AI initiatives. Cleaning it is valuable and measurable.", build: "Build a scheduled CRM audit that paginates records, normalizes names/domains/phones/stages, detects stale ownership and duplicates, creates exceptions, and sends a daily health report.", patterns: ["Schedule Trigger", "HTTP Request", "Loop Over Items", "Code", "Postgres", "Error Trigger"], fundamentals: ["cursor pagination", "batching", "async Promises", "regex", "SQL", "indexes", "backoff"], drills: ["Fetch a paginated API until the cursor ends", "Normalize a batch of names and phone numbers", "Store a batch checkpoint in Postgres", "Send a daily health summary from stored results"], tests: ["10,000-record import completes in bounded batches", "A partial batch failure resumes from its checkpoint", "429 responses use exponential backoff with a retry cap", "Duplicate/stale records enter an exception queue", "Dead-letter items can be replayed without corruption"], gate: "A large batch can fail halfway, resume safely, and never corrupt or duplicate data.", content: "Case-study demo: before/after data health metrics and the failure-recovery path." },
    {
      id: "P04", slug: "p04", title: "Multi-System Data Sync", value: "Cross-system handoffs are where revenue and operations data quietly breaks.", build: "Build a two-way sync between a CRM, database, spreadsheet, or ERP sandbox with a defined source of truth, conflict rules, timestamps, external IDs, and replay logic.", patterns: ["Schedule Trigger", "Webhook", "Merge", "Code", "Postgres", "Execute Workflow"], fundamentals: ["source of truth", "conflict handling", "timestamps", "queues", "replay", "event ordering"], drills: ["Define ownership for each field across two systems", "Sync one changed record with an external ID", "Detect and flag a conflicting edit", "Replay one failed record from a runbook"], tests: ["Source-of-truth rules resolve conflicting edits consistently", "Out-of-order events do not overwrite newer data", "Retry never duplicates a downstream record", "Missing external IDs create an exception", "A failed record can be replayed by ID"], gate: "You can point to every field’s source of truth and explain why retries cannot corrupt it.", content: "Explain one real data-conflict scenario and the rule that resolves it." },
    {
      id: "P05", slug: "p05", title: "Invoice / Quote Reconciliation Desk", value: "Finance teams pay for reliable exception handling because errors hit cash, trust, and auditability.", build: "Ingest test invoices or payments, extract strict structured fields, match them to CRM/accounting records, flag mismatches, and require human approval before any accounting update.", patterns: ["Webhook", "HTTP Request", "Code", "Postgres", "Wait", "Error Trigger"], fundamentals: ["SQL joins", "constraints", "transactions", "audit logs", "webhook signatures", "structured LLM outputs"], drills: ["Verify a signed invoice webhook", "Match invoice fields to CRM records with SQL", "Parse a document into a fixed JSON schema", "Create an approval state and immutable audit entry"], tests: ["Duplicate invoice events create one reconciliation record", "Ambiguous matches require human review", "Malformed invoice data never updates accounting", "Approved retry creates one final outcome", "Signature verification rejects altered payloads"], gate: "Ambiguous, duplicate, malformed, and retried invoices all reach one correct and auditable outcome.", content: "High-value demo: show how exceptions—not blind automation—protect finance operations." },
    {
      id: "P06", slug: "p06", title: "Customer Onboarding Orchestrator", value: "Fast, error-free onboarding turns closed revenue into activated customers.", build: "Build signed payment/contract event → customer workspace → role assignment → third-party provisioning → onboarding tasks → welcome flow.", patterns: ["Webhook", "Switch", "Wait", "Execute Workflow", "HTTP Request", "Error Trigger"], fundamentals: ["state machines", "OAuth refresh", "RBAC", "compensating actions", "eventual consistency", "secrets"], drills: ["Model onboarding as explicit states", "Provision a sandbox account using OAuth", "Assign a role using least privilege", "Create a recovery path for one failed provisioning step"], tests: ["Duplicate payment event cannot create duplicate accounts", "Expired OAuth token refreshes or creates a visible exception", "Partial provisioning exposes current state and recovery action", "Privileged action needs explicit approval", "Stale onboarding state times out and alerts"], gate: "Every partial failure has a documented recovery path without duplicate accounts or lost state.", content: "Show the state machine—not just the happy path—to demonstrate serious engineering." },
    {
      id: "P07", slug: "p07", title: "AI Support + SLA System", value: "AI is valuable only when it improves speed without creating unsafe external actions.", build: "Build ticket/email intake → constrained classification → priority → reply draft → human approval → SLA escalation, with explicit safety and cost boundaries.", patterns: ["Email Trigger", "AI node / HTTP Request", "Code", "Switch", "Wait", "Error Trigger"], fundamentals: ["JSON Schema", "prompt injection", "evaluations", "confidence thresholds", "token cost", "PII"], drills: ["Force an LLM response into a strict schema", "Create a low-confidence human-review route", "Add a prompt-injection test ticket", "Run a fixed evaluation set after changing a prompt"], tests: ["Injected instructions cannot alter external actions", "Low-confidence classification routes to humans", "Schema-invalid AI output is rejected", "Token/cost threshold stops excess volume", "No reply is sent without explicit approval"], gate: "A malicious ticket cannot change system behavior, and prompt changes pass a regression evaluation.", content: "Teach the difference between safe AI assistance and an unsafe autonomous agent." },
    {
      id: "P08", slug: "p08", title: "Self-Hosted n8n Operations", value: "Reliable delivery and retainers require you to understand where automations run, fail, and recover.", build: "Build your own non-client n8n environment with Docker Compose, Postgres, HTTPS, encrypted credentials, retention rules, backups, monitoring, staging, and production.", patterns: ["Error Trigger", "Execute Workflow", "Postgres", "credentials", "queue mode"], fundamentals: ["Linux", "Docker", "DNS/TLS", "secrets", "backups", "logs", "monitoring", "incident response"], drills: ["Run n8n and Postgres with Docker Compose", "Configure execution retention", "Back up and restore a workflow/state database", "Write a rollback and incident runbook"], tests: ["Restore works in a clean environment", "Secrets never enter Git", "Execution data is pruned on schedule", "A failed workflow creates an alert", "Staging changes do not alter production"], gate: "You can restore the system from backup and explain the recovery process to a client.", content: "Document the restore rehearsal. Reliability content is more credible than another node tutorial." },
    {
      id: "P09", slug: "p09", title: "RevOps Control Tower", value: "This turns recurring automation exceptions into a product-quality operator experience.", build: "Build a Next.js + Supabase app for approvals, exceptions, execution history, and workflow metrics after the automation projects themselves work.", patterns: ["Supabase", "Next.js server actions", "Postgres", "webhook integration", "approval workflows"], fundamentals: ["TypeScript", "React", "migrations", "AuthN vs AuthZ", "Row-Level Security", "testing", "deployment"], drills: ["Design an organization/member/role schema", "Write an RLS policy for a tenant-owned record", "Render a failed execution and retry action", "Test two organizations with separate data"], tests: ["Tenant A cannot view Tenant B records", "Tenant A cannot approve Tenant B exceptions", "Audit log records each approval", "A retry action is permission-checked", "Secrets remain server-side"], gate: "Two organizations cannot access, infer, or approve each other’s data.", content: "Only build this after client work reveals the same exception workflow repeatedly." }
  ]
};
